Feature/ser 80
idealisconsultingbe/Serel pull request #15
Opened 2021-11-26 13:42 UTC by raoua28

2021-11-29 06:42 UTC, idealisconsultingbe requested changes

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp_production/models/mrp_production.py
> +        Return  product sticker report if product_uom_qty has equals move.reserved_availability
return if? There's no if in the code

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp_production/models/stock_move.py
> +            move.is_print = True
This has to be optimized! 
It should be self.write({'is_print': True}) instead of these 2 lines

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp_production/report/serel_stickers.xml
> +    <record id="serel_stickers_format" model="report.paperformat">
Why defining a new paperformat? The same actually exists and is sued for the 51x25 sticker in the module serel_product_advised_price

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp_production/views/stock_move_views.xml
> +        <field name="name">stock.move.view.tree</field>
view.tree.**inherit**

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp_production/views/stock_move_views.xml
> +        <field name="name">stock.move.view.form</field>
stock.move.view.form.inherit

2021-11-29 06:42 UTC, idealisconsultingbe commented on serel_mrp/security/ir.model.access.csv
> +access_mrp_production_all,access_mrp_production_all,serel_mrp.model_stock_move,,1,1,1,1
Why giving all accesses to the stock.move model? There is no group specified

2021-11-29 13:52 UTC, idealisconsultingbe requested changes

2021-11-30 08:27 UTC, rraidealis requested changes

2021-11-30 08:27 UTC, rraidealis commented on serel_mrp/__manifest__.py
> +    'depends': ['serel_core', 'serel_product_advised_price'],
serel_product_advised_price depends of serel_core, so serel_core is unnecessary in the depends here

2021-11-30 08:38 UTC, merged