[SS22-21][ADD] serel_hr_expense: add new module serel_hr_expense + nu…
idealisconsultingbe/Serel pull request #37
Opened 2022-12-07 13:52 UTC by idealisconsultingbe

…mbering on expense sheets + merge pdf attachments from expenses in expense sheets reports

2022-12-08 07:48 UTC, rraidealis requested changes
Hello Mathias, j'ai fait le code review avec les différentes remarques. Comme d'habitude, n'hésite pas à me contacter si tu as des questions

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/__manifest__.py
> +    'depends': ['serel_core'],
Où est la dépendance vers le module hr_expense?

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/__manifest__.py
> +    'currency': 'EUR',
Pas nécessaire de mettre le prix et la devise dans un module custo et gratuit

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/hr_expense_sheet.py
> +from collections import OrderedDict
Ordre des librairies importées : https://www.odoo.com/documentation/16.0/contributing/development/coding_guidelines.html#imports

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/hr_expense_sheet.py
> +    numbering = fields.Char('Number', required=True, readonly=True, default=lambda self: _('New'))
default='New' aurait suffi ici, de plus pas besoin d'appeler la fonction _ avant. 
Par défaut Odoo proposera de traduire chaque attribut qui est un String dans la déclaration des champs

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/hr_expense_sheet.py
> +    def _get_attachments(self):
Que fait cette méthode? Utiliser Docstrings

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/hr_expense_sheet.py
> +            if next_code_digits_count == 1:
J'ai le sentiment qu'un zfill pourrait largement alléger ton code : https://www.w3schools.com/python/ref_string_zfill.asp

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/hr_expense_sheet.py
> +    def create(self, vals):
Que fait la méthode? Docstrings!

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/models/ir_actions_report.py
> +        """
Ok pour l'héritage, mais vu que tu as repris du code standard, peux-tu signaler où tu as fait les modifs custo dans cette méthode stp

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/report/hr_expense_report.xml
> +    <record id="hr_expense.action_report_hr_expense_sheet" model="ir.actions.report">
Pourquoi avoir modifié l'ir.actions.report? Ce n'est pas nécessaire vu que ton template hérite du report standard qui est appélé à partir de l'ir.actions.report `action_report_hr_expense_sheet`

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/scripts/python_odoo_set_first_numberings.py
> +# import pdb; # pdb.set_trace()
Code commenté à enlever

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/scripts/python_odoo_set_first_numberings.py
> +import logging
Pourquoi ton import n'est pas avec les autres? + Respecter ordering

2022-12-08 07:48 UTC, rraidealis commented on serel_hr_expense/scripts/python_odoo_set_first_numberings.py
> +    for record in records:
La boucle fait exactement le même que dans la méthode create. On a du code dupliqué, il faudrait créer une nouvelle méthode dans hr.expense, qui reprend cette logique, et qui est appelée à partir du script et de la méthode create

2022-12-08 09:28 UTC, idealisconsultingbe commented on serel_hr_expense/__manifest__.py
> +    'depends': ['serel_core'],
Ah oui c'est vrai.. je pensais qu'elle était dans serel_core mais non, je la rajoute

2022-12-08 09:31 UTC, idealisconsultingbe commented on serel_hr_expense/models/hr_expense_sheet.py
> +from collections import OrderedDict
en effet, merci

2022-12-08 09:33 UTC, idealisconsultingbe commented on serel_hr_expense/models/hr_expense_sheet.py
> +    numbering = fields.Char('Number', required=True, readonly=True, default=lambda self: _('New'))
J'ai repris ça du champ "name" du modèle "sale.order", mais en effet je pouvais juste mettre default='New', merci pour la remarque

2022-12-08 09:54 UTC, idealisconsultingbe commented on serel_hr_expense/report/hr_expense_report.xml
> +    <record id="hr_expense.action_report_hr_expense_sheet" model="ir.actions.report">
ah en effet.. je pensais qu'il fallait du coup préciser de prendre celui de notre module serel_hr_expense. J'ai enlevé du coup, merci!

2022-12-09 08:47 UTC, rraidealis approved these changes

2022-12-09 08:48 UTC, merged